### ISSUE TITLE
Error while getting access token

### ISSUE THREAD

**Issue by meewarwoowoo** [AlbertKozlowski/Twitter-php#1]
I've installed this and when using it I get the following error:

Fatal error: Uncaught exception 'TwitterPhp\RestApiException' with message 'Error while getting access token' in C:\Server\htdocs\Twitter-php\connection\Application.php:77 Stack trace: #0 C:\Server\htdocs\Twitter-php\connection\Application.php(43): TwitterPhp\Connection\Application->_getBearerToken() #1 C:\Server\htdocs\Twitter-php\connection\ConnectionAbstract.php(62): TwitterPhp\Connection\Application->_buildHeaders('https://api.twi...', Array, 'GET') #2 C:\Server\htdocs\gj-generic-form.html(203): TwitterPhp\Connection\Base->get('/statuses/user_...', Array) #3 {main} thrown in C:\Server\htdocs\Twitter-php\connection\Application.p

I've checked my secret/key and they are as they should be.

**Comment by AlbertKozlowski** [comment]
Hello, 

Thanks you for you report. 
This issue is related to [curl outdated certificates](http://stackoverflow.com/questions/316099/cant-connect-to-https-site-using-curl-returns-0-length-content-instead-what-c#answer-316732)

Unfortunately I have to make a minor changes to the code, so it will be possible to pass configuration to CURL to solve this issue on Windows machines.

**Comment by meewarwoowoo** [comment]
Thanks for the speedy response.  I'll keep an eye on the update and test this.  Thanks.

**Comment by AlbertKozlowski** [comment]
Here is temporary solution, that should fix your issue with all ssl request via CURL. 

http://stackoverflow.com/questions/2694787/how-can-i-set-curlopt-cainfo-globally-for-php-on-windows

Besides that, still I have to update this code because passing configuration for twitter request might be useful. Let me know if this solution above fix your issue.
